from django.apps import AppConfig


class ToolsConfig(AppConfig):
    name = 'tools'

RACE_ICONS = {
    'Human': 'UI/Glues/Loading/Backgrounds/Campaigns/HumanSymbol.blp',
    'Orc': 'UI/Glues/Loading/Backgrounds/Campaigns/OrcSymbol.blp',
    'NightElf': 'UI/Glues/Loading/Backgrounds/Campaigns/NightElfSymbol.blp',
    'Undead': 'UI/Glues/Loading/Backgrounds/Campaigns/UndeadSymbol.blp',
}

ICONS_DIR = 'ReplaceableTextures/CommandButtons'

CATEGORIZATION = {
    'ChaosWarlockGreen': ('campaign'),
    'GoblinLandMine': ('special'),
    'Medivh': ('campaign', 'heroic'),
    'SpiritPig': ('special'),
    'SylvanusWindrunner': ('campaign', 'heroic'),
    'AncestralGuardian': ('special'),
    'TempArt': ('special'),
    'WindSerpent': ('special'),
    'ChaosSpaceOrc': ('campaign'),
    'ElfVillagerWoman': ('campaign'),
    'HighElfPeasant': ('campaign'),
    'Hydralisk': ('campaign'),
    'Marine': ('campaign'),
    'OrcJuggernaught': ('campaign'),
    'SammyCube': ('special'),
    'Shoveler': ('special'),
    'VillagerKid': ('campaign'),
    'VillagerKid1': ('campaign'),
    'VillagerMan': ('campaign'),
    'VillagerMan1': ('campaign'),
    'VillagerWoman': ('campaign'),
    'Zergling': ('campaign'),
    'FlyingSheep': ('campaign', 'special'),
    'Hellscream': ('campaign', 'heroic'),
    'ChaosGrunt': ('campaign'),
    'ChaosHellscream': ('campaign', 'heroic'),
    'ChaosKotoBeast': ('campaign'),
    'ChaosOrcRange': ('campaign'),
    'ChaosPeon': ('campaign'),
    'ChaosWarlock': ('campaign'),
    'ChaosWarlord': ('campaign'),
    'ChaosWolfrider': ('campaign'),
    'DoomGuard': ('campaign'),
    'HeroChaosBladeMaster': ('campaign', 'heroic'),
    'Infernal': ('campaign'),
    'Mannoroth': ('campaign', 'heroic'),
    'Pitlord': ('campaign', 'heroic'),
    'Warlock': ('campaign'),
    'felhound': ('campaign'),
    'Arthas': ('campaign', 'heroic'),
    'ArthaswithSword': ('campaign', 'heroic'),
    'HeroArchMage': ('heroic'),
    'HeroMountainKing': ('heroic'),
    'HeroPaladin': ('heroic'),
    'HeroPaladinBoss': ('campaign', 'heroic'),
    'HeroPaladinBoss2': ('campaign', 'heroic'),
    'Jaina': ('campaign', 'heroic'),
    'KnightNoRider': ('campaign', 'special'),
    'Militia': ('special'),
    'Muradin': ('campaign', 'heroic'),
    'TheCaptain': ('campaign'),
    'Uther': ('campaign', 'heroic'),
    'WarWagon': ('campaign', 'special'),
    'WaterElemental': ('special'),
    'Ent': ('special'),
    'Furion': ('campaign', 'heroic'),
    'HeroDemonHunter': ('heroic'),
    'HeroKeeperOfTheGrove': ('heroic'),
    'HeroKeeperoftheGroveGhost': ('campaign', 'heroic'),
    'HeroMoonPriestess': ('heroic'),
    'Illidan': ('campaign', 'heroic'),
    'Owl': ('special'),
    'OwlSCOUT': ('special'),
    'RiddenHippoGryph': ('special'),
    'Shandris': ('campaign', 'heroic'),
    'Tyrande': ('campaign', 'heroic'),
    'AncestralGuardian': ('special'),
    'Cairne': ('campaign', 'heroic'),
    'HealingWard': ('special'),
    'Hellscream': ('campaign', 'heroic'),
    'HeroBladeMaster': ('heroic'),
    'HeroFarseer': ('heroic'),
    'HeroTaurenChieftain': ('heroic'),
    'HeroTaurenChieftainCIN': ('campaign', 'heroic'),
    'KotoBeastNoRider': ('campaign'),
    'RiderlessWyvern': ('campaign'),
    'SentryWard': ('special'),
    'Spiritwolf': ('special'),
    'StasisTotem': ('special'),
    'Thrall': ('heroic'),
    'AbominationCIN': ('campaign'),
    'EvilArthas': ('campaign', 'heroic'),
    'HeroDeathKnight': ('heroic'),
    'HeroDreadLord': ('heroic'),
    'HeroLich': ('heroic'),
    'HeroLichCIN': ('campaign', 'heroic'),
    'KelThuzadLich': ('campaign', 'heroic'),
    'KelThuzadNecro': ('campaign', 'heroic'),
    'Kelthuzad': ('campaign', 'heroic'),
    'KelthuzadGhost': ('campaign', 'heroic'),
    'PlagueCloud': ('special'),
    'Skeleton': ('special'),
    'Tichondrius': ('campaign', 'heroic'),
}

REPLACEABLE_ICONS = {
    'ElfVillagerWoman': 'FemaleElfVillager',
    'BlackStagMale': 'Stag',
    'BrownWolf': 'DireWolf',
    'SammyCube': 'SelectHeroOn',
    'Rat': 'YouDirtyRat!',
    'OrcJuggernaught': 'Juggernaut',
    'HighElfPeasant': 'ElfVillager',
    'VillagerKid1': 'VillagerKid2',
    'zergling': 'Zergling',
    'FlyingSheep': 'Sheep',
    'WhiteWolf': 'TimberWolf',
    'WendigoShaman': 'Wendigo',
    'BansheeGhost': 'Ghost',
    'Watcher': 'AvengingWatcher',
    'WindSerpent': 'SelectHeroOn',
    'NerubianSpiderLord': 'nerubianSpiderLord',
    'HumanMage': 'BanditMage',
    'BronzeDragonWelp': 'BronzeDragon',
    'BurningArcher': 'SkeletonArcher',
    'RazorManeChief': 'RazormaneChief',
    'GnollOverSeer': 'GnollKing',
    'BlackDragonWelp': 'BlackDragon',
    'BristleBack': 'Razorback',
    'RedDragonWelp': 'RedDragon',
    'ForestTrollTrapper': 'ForestTrollTrapper',
    'IronGolem': 'ArmorGolem',
    'AzureDragonWelp': 'AzureDragon',
    'TempArt': 'SelectHeroOn',
    'SpiritPig': 'Pig',
    'HighElfArcher': 'HighElvenArcher',
    'SludgeMonster': 'SludgeCreature',
    'satyrhellcaller': 'SatyrTrickster',
    'RazorMane': 'Razorback',
    'GolemStatue': 'ArmorGolem',
    'MurlocWarrior': 'Murloc',
    'Owlbear': 'OwlBear',
    'SylvanusWindrunner': 'SylvanusWindRunner',
    'GreenDragonWelp': 'GreenDragon',
    'ChaosWolfrider': 'ChaosWolfRider',
    'ChaosOrcRange': 'SelectHeroOn',
    'ChaosHellscream': 'ChaosGrom',
    'HeroChaosBladeMaster': 'ChaosBlademaster',
    'Pitlord': 'PitLord',
    'felhound': 'FelHound',
    'Warlock': 'OrcWarlockRed',
    'Muradin': 'HeroMountainKing',
    'GyroCopter': 'Gyrocopter',
    'HeroPaladinBoss2': 'HeroPaladin',
    'WarWagon': 'SeigeEngine',
    'KnightNoRider': 'RiderlessHorse',
    'ArthaswithSword': 'Arthas',
    'HeroPaladinBoss': 'HeroPaladin',
    'WaterElemental': 'SummonWaterElemental',
    'Uther': 'HeroPaladin',
    'Meatwagon': 'MeatWagon',
    'HeroLichCIN': 'LichVersion2',
    'Kelthuzad': 'KelThuzad',
    'KelthuzadGhost': 'GhostOfKelThuzad',
    'KelThuzadLich': 'KelThuzad',
    'KelThuzadNecro': 'GhostOfKelThuzad',
    'Skeleton': 'SkeletonWarrior',
    'AbominationCIN': 'Abomination',
    'EvilArthas': 'HeroDeathKnight',
    'Tyrande': 'HeroMoonPriestess',
    'RiddenHippoGryph': 'HippogriffRider',
    'HippoGryph': 'Hippogriff',
    'HeroKeeperOfTheGrove': 'KeeperOfTheGrove',
    'Illidan': 'HeroDemonHunter',
    'OwlSCOUT': 'Scout',
    'Owl': 'OwlBear',
    'HeroKeeperoftheGroveGhost': 'KeeperGhostBlue',
    'HeroBladeMaster': 'HeroBlademaster',
    'RiderlessWyvern': 'Wyvern',
    'HeroTaurenChieftainCIN': 'HeroTaurenChieftain',
    'AncestralGuardian': 'SelectHeroOn',
    'Cairne': 'HeroTaurenChieftain',
    'Wolfrider': 'Raider',
    'StasisTotem': 'StasisTrap',
    'KotoBeastNoRider': 'RiderlessKodo',
    'Hellscream': 'HellScream',
    'HeadHunter': 'Headhunter',
    'Spiritwolf': 'SpiritWolf',
}
