from django.apps import AppConfig


class ToolsConfig(AppConfig):
    name = 'tools'

RACE_ICONS = {
    'Human': 'UI/Glues/Loading/Backgrounds/Campaigns/HumanSymbol.blp',
    'Orc': 'UI/Glues/Loading/Backgrounds/Campaigns/OrcSymbol.blp',
    'NightElf': 'UI/Glues/Loading/Backgrounds/Campaigns/NightElfSymbol.blp',
    'Undead': 'UI/Glues/Loading/Backgrounds/Campaigns/UndeadSymbol.blp',
}

REPLACEABLE_ICONS_PATH = 'ReplaceableTextures/CommandButtons'

REPLACEABLE_EQUIVALENCE = {
    'ElfVillagerWoman': 'FemaleElfVillager',
    'BlackStagMale': 'Stag',
    'BrownWolf': 'DireWolf',
    'SammyCube': 'SelectHeroOn',
    'Rat': 'YouDirtyRat!',
    'OrcJuggernaught': 'Juggernaut',
    'HighElfPeasant': 'ElfVillager',
    'VillagerKid1': 'VillagerKid2',
    'zergling': 'Zergling',
    'FlyingSheep': 'Sheep',
    'WhiteWolf': 'TimberWolf',
    'WendigoShaman': 'Wendigo',
    'BansheeGhost': 'Ghost',
    'Watcher': 'AvengingWatcher',
    'WindSerpent': 'SelectHeroOn',
    'NerubianSpiderLord': 'nerubianSpiderLord',
    'HumanMage': 'BanditMage',
    'BronzeDragonWelp': 'BronzeDragon',
    'BurningArcher': 'SkeletonArcher',
    'RazorManeChief': 'RazormaneChief',
    'GnollOverSeer': 'GnollKing',
    'BlackDragonWelp': 'BlackDragon',
    'BristleBack': 'Razorback',
    'RedDragonWelp': 'RedDragon',
    'ForestTrollTrapper': 'ForestTrollTrapper',
    'IronGolem': 'ArmorGolem',
    'AzureDragonWelp': 'AzureDragon',
    'TempArt': 'SelectHeroOn',
    'SpiritPig': 'Pig',
    'HighElfArcher': 'HighElvenArcher',
    'SludgeMonster': 'SludgeCreature',
    'satyrhellcaller': 'SatyrTrickster',
    'RazorMane': 'Razorback',
    'GolemStatue': 'ArmorGolem',
    'MurlocWarrior': 'Murloc',
    'Owlbear': 'OwlBear',
    'SylvanusWindrunner': 'SylvanusWindRunner',
    'GreenDragonWelp': 'GreenDragon',
    'ChaosWolfrider': 'ChaosWolfRider',
    'ChaosOrcRange': 'SelectHeroOn',
    'ChaosHellscream': 'ChaosGrom',
    'HeroChaosBladeMaster': 'ChaosBlademaster',
    'Pitlord': 'PitLord',
    'felhound': 'FelHound',
    'Warlock': 'OrcWarlockRed',
    'Muradin': 'HeroMountainKing',
    'GyroCopter': 'Gyrocopter',
    'HeroPaladinBoss2': 'HeroPaladin',
    'WarWagon': 'SeigeEngine',
    'KnightNoRider': 'RiderlessHorse',
    'ArthaswithSword': 'Arthas',
    'HeroPaladinBoss': 'HeroPaladin',
    'WaterElemental': 'SummonWaterElemental',
    'Uther': 'HeroPaladin',
    'Meatwagon': 'MeatWagon',
    'HeroLichCIN': 'LichVersion2',
    'Kelthuzad': 'KelThuzad',
    'KelthuzadGhost': 'GhostOfKelThuzad',
    'KelThuzadLich': 'KelThuzad',
    'KelThuzadNecro': 'GhostOfKelThuzad',
    'Skeleton': 'SkeletonWarrior',
    'AbominationCIN': 'Abomination',
    'EvilArthas': 'HeroDeathKnight',
    'Tyrande': 'HeroMoonPriestess',
    'RiddenHippoGryph': 'HippogriffRider',
    'HippoGryph': 'Hippogriff',
    'HeroKeeperOfTheGrove': 'KeeperOfTheGrove',
    'Illidan': 'HeroDemonHunter',
    'OwlSCOUT': 'Scout',
    'Owl': 'OwlBear',
    'HeroKeeperoftheGroveGhost': 'KeeperGhostBlue',
    'HeroBladeMaster': 'HeroBlademaster',
    'RiderlessWyvern': 'Wyvern',
    'HeroTaurenChieftainCIN': 'HeroTaurenChieftain',
    'AncestralGuardian': 'SelectHeroOn',
    'Cairne': 'HeroTaurenChieftain',
    'Wolfrider': 'Raider',
    'StasisTotem': 'StasisTrap',
    'KotoBeastNoRider': 'RiderlessKodo',
    'Hellscream': 'HellScream',
    'HeadHunter': 'Headhunter',
    'Spiritwolf': 'SpiritWolf',
}
